### obtener todos los user
GET http://localhost:3000/api/users

###Obtener un usuario uitilizando id
GET http://localhost:3000/api/users/1

###Crear un nuevo usuario. ¿¿¿Cómo agrego la fecha???
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "firstName": "Pepe",
    "lastName": "Hildfdfebrandt",
    "email": "3232@gmail.com"
}


###Cambiar un Usuario
PUT http://localhost:3000/api/users/3
Content-Type: application/json

{
    "firstName": "Pedro",
    "lastName": "Hilman",
    "email": "hilmanp@gmail.com"

}

### Modificaciones a un Usuario con PATCH
PATCH  http://localhost:3000/api/users/5
Content-Type: application/json

{
    "firstName": "Gastón",
    "lastName": "Rodriguez"

}


###Borrar un usuario
DELETE http://localhost:3000/api/users/1

